<a href="https://colab.research.google.com/github/mrojash97/dataanalytics/blob/main/Python/AN%C3%81LISIS_EDA_Supermarket_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **📊Análisis Exploratorio de Datos - Supermarket Sales**
**Autor:** MARLON ROJAS HUARIPATA  
**Fecha:** 04/2025  
**Descripción:** Exploraremos y visualizaremos los datos de ventas de un supermercado. Dataset obtenida de Kaggle.

## 📑 Tabla de Contenidos

1. [📘 Objetivos ](#obj)
2. [🛠️ Importación de Librerias](#lib)
3. [🔄 Carga de Datos](#datos)
4. [📑 Preparando Datos](#prep)
5. [📊 Análisis Exploratorio de Datos (EDA)](#eda)
6. [📈 Visualizaciones Interactivas](#vis)
7. [🛠️ Herramientas y Utilidades](#tools)
8. [📦 Proyectos Destacados](#proyectos)
9. [📚 Recursos y Enlaces](#recursos)

### **📘 Objetivos** <a name="obj"></a>

**Objetivo Principal:**

Evaluar y comprender el comportamiento de las ventas en las sedes, los productos, los clientes, para tomar decisiones informadas que optimicen los procesos comerciales, aumenten la rentabilidad y mejoren la experiencia del cliente.

**Objetivos Específicos:**

1. **Identificar patrones de compra:** Conocer las preferencias de consumo por sucursal, categoría de producto y método de pago para determinar las sucursales y líneas de producto más rentables.
2. **Evaluar la demanda de los productos:**  Conocer la demanda de los productos, por sede, categoría y  la evolución de ventas mensuales, para enfocar las estrategias de marketing.
3. **Mejorar la gestión de personal y productos:** Conocer los días y horas de mayor actividad, para organizar al personal y tener mayor control del inventario.
4. **Evaluación de clientes:** Evaluar las calificaciones por sucursal, tipo de cliente, método de pago, línea de producto. Para entender el comportamiento del consumidor al calificar y mejorar su experiencia.

### **🛠️ Importación de Librerias** <a name="lib"></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### **🔄 Carga de Datos** <a name="datos"></a>

In [2]:
#Cargar datos
url_data="https://drive.google.com/uc?id=1oaCwwTcv1FsT9gNAZAxFbEcdCnuaW04C"

data = pd.read_csv(url_data)
#Mostrar datos
print(data.shape)
data.head(5)

(1000, 17)

,invoice_id,branch,city,customer_type,gender_customer,product_line,unit_cost,quantity,5pct_markup,revenue,date,time,payment_method,cogs,gm_pct,gross_income,rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,01/05/19,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,03/08/19,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,03/03/19,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,02/08/19,10:37,Ewallet,604.17,4.761905,30.2085,5.3

### **📑 Preparando Datos** <a name="prep"></a>

In [3]:
#Información de la base de datos
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   invoice_id       1000 non-null   object
 1   branch           1000 non-null   object
 2   city             1000 non-null   object
 3   customer_type    1000 non-null   object
 4   gender_customer  1000 non-null   object
 5   product_line     1000 non-null   object
 6   unit_cost        1000 non-null   float64
 7   quantity         1000 non-null   int64
 8   5pct_markup      1000 non-null   float64
 9   revenue          1000 non-null   float64
 10  date             1000 non-null   object
 11  time             1000 non-null   object
 12  payment_method   1000 non-null   object
 13  cogs             1000 non-null   float64
 14  gm_pct           1000 non-null   float64
 15  gross_income     1000 non-null   float64
 16  rating           1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [4]:
#Ver la cantidad de datos y variables
data.shape

(1000, 17)

In [5]:
#Validar si tenemos datos nulos
data.isnull().sum()

invoice_id         0
branch             0
city               0
customer_type      0
gender_customer    0
product_line       0
unit_cost          0
quantity           0
5pct_markup        0
revenue            0
date               0
time               0
payment_method     0
cogs               0
gm_pct             0
gross_income       0
rating             0
dtype: int64

In [6]:
#Validar si tenemos datos duplicados
data.duplicated().sum()

np.int64(0)

In [7]:
#Usamos data.to_dict(orient='records') para convertir cada fila del DataFrame en un diccionario, donde las claves son los nombres de las columnas y los valores son los valores correspondientes en cada fila.
ventas = data.to_dict(orient='records'),
print (ventas)

([{'invoice_id': '750-67-8428', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Health and beauty', 'unit_cost': 74.69, 'quantity': 7, '5pct_markup': 26.1415, 'revenue': 548.9715, 'date': '01/05/19', 'time': '13:08', 'payment_method': 'Ewallet', 'cogs': 522.83, 'gm_pct': 4.761904762, 'gross_income': 26.1415, 'rating': 9.1}, {'invoice_id': '226-31-3081', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Electronic accessories', 'unit_cost': 15.28, 'quantity': 5, '5pct_markup': 3.82, 'revenue': 80.22, 'date': '03/08/19', 'time': '10:29', 'payment_method': 'Cash', 'cogs': 76.4, 'gm_pct': 4.761904762, 'gross_income': 3.82, 'rating': 9.6}, {'invoice_id': '631-41-3108', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Home and lifestyle', 'unit_cost': 46.33, 'quantity': 7, '5pct_markup': 16.2155, 'revenue': 340.5255, 'date': '03/03/19', 'time': '13:23', 'payment_method': 'Credit card', 'cogs': 324.31, 'gm_pct': 4.761904762, 'gross_income': 16.2155, 'rating': 7.4}, {'invoice_id': '123-19-1176', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Health and beauty', 'unit_cost': 58.22, 'quantity': 8, '5pct_markup': 23.288, 'revenue': 489.048, 'date': '1/27/2019', 'time': '20:33', 'payment_method': 'Ewallet', 'cogs': 465.76, 'gm_pct': 4.761904762, 'gross_income': 23.288, 'rating': 8.4}, {'invoice_id': '373-73-7910', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Sports and travel', 'unit_cost': 86.31, 'quantity': 7, '5pct_markup': 30.2085, 'revenue': 634.3785, 'date': '02/08/19', 'time': '10:37', 'payment_method': 'Ewallet', 'cogs': 604.17, 'gm_pct': 4.761904762, 'gross_income': 30.2085, 'rating': 5.3}, {'invoice_id': '699-14-3026', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Electronic accessories', 'unit_cost': 85.39, 'quantity': 7, '5pct_markup': 29.8865, 'revenue': 627.6165, 'date': '3/25/2019', 'time': '18:30', 'payment_method': 'Ewallet', 'cogs': 597.73, 'gm_pct': 4.761904762, 'gross_income': 29.8865, 'rating': 4.1}, {'invoice_id': '355-53-5943', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Electronic accessories', 'unit_cost': 68.84, 'quantity': 6, '5pct_markup': 20.652, 'revenue': 433.692, 'date': '2/25/2019', 'time': '14:36', 'payment_method': 'Ewallet', 'cogs': 413.04, 'gm_pct': 4.761904762, 'gross_income': 20.652, 'rating': 5.8}, {'invoice_id': '315-22-5665', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Home and lifestyle', 'unit_cost': 73.56, 'quantity': 10, '5pct_markup': 36.78, 'revenue': 772.38, 'date': '2/24/2019', 'time': '11:38', 'payment_method': 'Ewallet', 'cogs': 735.6, 'gm_pct': 4.761904762, 'gross_income': 36.78, 'rating': 8.0}, {'invoice_id': '665-32-9167', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Health and beauty', 'unit_cost': 36.26, 'quantity': 2, '5pct_markup': 3.626, 'revenue': 76.146, 'date': '01/10/19', 'time': '17:15', 'payment_method': 'Credit card', 'cogs': 72.52, 'gm_pct': 4.761904762, 'gross_income': 3.626, 'rating': 7.2}, {'invoice_id': '692-92-5582', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Food and beverages', 'unit_cost': 54.84, 'quantity': 3, '5pct_markup': 8.226, 'revenue': 172.746, 'date': '2/20/2019', 'time': '13:27', 'payment_method': 'Credit card', 'cogs': 164.52, 'gm_pct': 4.761904762, 'gross_income': 8.226, 'rating': 5.9}, {'invoice_id': '351-62-0822', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Fashion accessories', 'unit_cost': 14.48, 'quantity': 4, '5pct_markup': 2.896, 'revenue': 60.816, 'date': '02/06/19', 'time': '18:07', 'payment_method': 'Ewallet', 'cogs': 57.92, 'gm_pct': 4.761904762, 'gross_income': 2.896, 'rating': 4.5}, {'invoice_id': '529-56-3974', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Electronic accessories', 'unit_cost': 25.51, 'quantity': 4, '5pct_markup': 5.102, 'revenue': 107.142, 'date': '03/09/19', 'time': '17:03', 'payment_method': 'Cash', 'cogs': 102.04, 'gm_pct': 4.761904762, 'gross_income': 5.102, 'rating': 6.8}, {'invoice_id': '365-64-0515', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Electronic accessories', 'unit_cost': 46.95, 'quantity': 5, '5pct_markup': 11.7375, 'revenue': 246.4875, 'date': '02/12/19', 'time': '10:25', 'payment_method': 'Ewallet', 'cogs': 234.75, 'gm_pct': 4.761904762, 'gross_income': 11.7375, 'rating': 7.1}, {'invoice_id': '252-56-2699', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Food and beverages', 'unit_cost': 43.19, 'quantity': 10, '5pct_markup': 21.595, 'revenue': 453.495, 'date': '02/07/19', 'time': '16:48', 'payment_method': 'Ewallet', 'cogs': 431.9, 'gm_pct': 4.761904762, 'gross_income': 21.595, 'rating': 8.2}, {'invoice_id': '829-34-3910', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Health and beauty', 'unit_cost': 71.38, 'quantity': 10, '5pct_markup': 35.69, 'revenue': 749.49, 'date': '3/29/2019', 'time': '19:21', 'payment_method': 'Cash', 'cogs': 713.8, 'gm_pct': 4.761904762, 'gross_income': 35.69, 'rating': 5.7}, {'invoice_id': '299-46-1805', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Sports and travel', 'unit_cost': 93.72, 'quantity': 6, '5pct_markup': 28.116, 'revenue': 590.436, 'date': '1/15/2019', 'time': '16:19', 'payment_method': 'Cash', 'cogs': 562.32, 'gm_pct': 4.761904762, 'gross_income': 28.116, 'rating': 4.5}, {'invoice_id': '656-95-9349', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Health and beauty', 'unit_cost': 68.93, 'quantity': 7, '5pct_markup': 24.1255, 'revenue': 506.6355, 'date': '03/11/19', 'time': '11:03', 'payment_method': 'Credit card', 'cogs': 482.51, 'gm_pct': 4.761904762, 'gross_income': 24.1255, 'rating': 4.6}, {'invoice_id': '765-26-6951', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Sports and travel', 'unit_cost': 72.61, 'quantity': 6, '5pct_markup': 21.783, 'revenue': 457.443, 'date': '01/01/19', 'time': '10:39', 'payment_method': 'Credit card', 'cogs': 435.66, 'gm_pct': 4.761904762, 'gross_income': 21.783, 'rating': 6.9}, {'invoice_id': '329-62-1586', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Food and beverages', 'unit_cost': 54.67, 'quantity': 3, '5pct_markup': 8.2005, 'revenue': 172.2105, 'date': '1/21/2019', 'time': '18:00', 'payment_method': 'Credit card', 'cogs': 164.01, 'gm_pct': 4.761904762, 'gross_income': 8.2005, 'rating': 8.6}, {'invoice_id': '319-50-3348', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Home and lifestyle', 'unit_cost': 40.3, 'quantity': 2, '5pct_markup': 4.03, 'revenue': 84.63, 'date': '03/11/19', 'time': '15:30', 'payment_method': 'Ewallet', 'cogs': 80.6, 'gm_pct': 4.761904762, 'gross_income': 4.03, 'rating': 4.4}, {'invoice_id': '300-71-4605', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Electronic accessories', 'unit_cost': 86.04, 'quantity': 5, '5pct_markup': 21.51, 'revenue': 451.71, 'date': '2/25/2019', 'time': '11:24', 'payment_method': 'Ewallet', 'cogs': 430.2, 'gm_pct': 4.761904762, 'gross_income': 21.51, 'rating': 4.8}, {'invoice_id': '371-85-5789', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Health and beauty', 'unit_cost': 87.98, 'quantity': 3, '5pct_markup': 13.197, 'revenue': 277.137, 'date': '03/05/19', 'time': '10:40', 'payment_method': 'Ewallet', 'cogs': 263.94, 'gm_pct': 4.761904762, 'gross_income': 13.197, 'rating': 5.1}, {'invoice_id': '273-16-6619', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Home and lifestyle', 'unit_cost': 33.2, 'quantity': 2, '5pct_markup': 3.32, 'revenue': 69.72, 'date': '3/15/2019', 'time': '12:20', 'payment_method': 'Credit card', 'cogs': 66.4, 'gm_pct': 4.761904762, 'gross_income': 3.32, 'rating': 4.4}, {'invoice_id': '636-48-8204', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Electronic accessories', 'unit_cost': 34.56, 'quantity': 5, '5pct_markup': 8.64, 'revenue': 181.44, 'date': '2/17/2019', 'time': '11:15', 'payment_method': 'Ewallet', 'cogs': 172.8, 'gm_pct': 4.761904762, 'gross_income': 8.64, 'rating': 9.9}, {'invoice_id': '549-59-1358', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Sports and travel', 'unit_cost': 88.63, 'quantity': 3, '5pct_markup': 13.2945, 'revenue': 279.1845, 'date': '03/02/19', 'time': '17:36', 'payment_method': 'Ewallet', 'cogs': 265.89, 'gm_pct': 4.761904762, 'gross_income': 13.2945, 'rating': 6.0}, {'invoice_id': '227-03-5010', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Home and lifestyle', 'unit_cost': 52.59, 'quantity': 8, '5pct_markup': 21.036, 'revenue': 441.756, 'date': '3/22/2019', 'time': '19:20', 'payment_method': 'Credit card', 'cogs': 420.72, 'gm_pct': 4.761904762, 'gross_income': 21.036, 'rating': 8.5}, {'invoice_id': '649-29-6775', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Fashion accessories', 'unit_cost': 33.52, 'quantity': 1, '5pct_markup': 1.676, 'revenue': 35.196, 'date': '02/08/19', 'time': '15:31', 'payment_method': 'Cash', 'cogs': 33.52, 'gm_pct': 4.761904762, 'gross_income': 1.676, 'rating': 6.7}, {'invoice_id': '189-17-4241', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Fashion accessories', 'unit_cost': 87.67, 'quantity': 2, '5pct_markup': 8.767, 'revenue': 184.107, 'date': '03/10/19', 'time': '12:17', 'payment_method': 'Credit card', 'cogs': 175.34, 'gm_pct': 4.761904762, 'gross_income': 8.767, 'rating': 7.7}, {'invoice_id': '145-94-9061', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Food and beverages', 'unit_cost': 88.36, 'quantity': 5, '5pct_markup': 22.09, 'revenue': 463.89, 'date': '1/25/2019', 'time': '19:48', 'payment_method': 'Cash', 'cogs': 441.8, 'gm_pct': 4.761904762, 'gross_income': 22.09, 'rating': 9.6}, {'invoice_id': '848-62-7243', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Health and beauty', 'unit_cost': 24.89, 'quantity': 9, '5pct_markup': 11.2005, 'revenue': 235.2105, 'date': '3/15/2019', 'time': '15:36', 'payment_method': 'Cash', 'cogs': 224.01, 'gm_pct': 4.761904762, 'gross_income': 11.2005, 'rating': 7.4}, {'invoice_id': '871-79-8483', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Fashion accessories', 'unit_cost': 94.13, 'quantity': 5, '5pct_markup': 23.5325, 'revenue': 494.1825, 'date': '2/25/2019', 'time': '19:39', 'payment_method': 'Credit card', 'cogs': 470.65, 'gm_pct': 4.761904762, 'gross_income': 23.5325, 'rating': 4.8}, {'invoice_id': '149-71-6266', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Sports and travel', 'unit_cost': 78.07, 'quantity': 9, '5pct_markup': 35.1315, 'revenue': 737.7615, 'date': '1/28/2019', 'time': '12:43', 'payment_method': 'Cash', 'cogs': 702.63, 'gm_pct': 4.761904762, 'gross_income': 35.1315, 'rating': 4.5}, {'invoice_id': '640-49-2076', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Sports and travel', 'unit_cost': 83.78, 'quantity': 8, '5pct_markup': 33.512, 'revenue': 703.752, 'date': '01/10/19', 'time': '14:49', 'payment_method': 'Cash', 'cogs': 670.24, 'gm_pct': 4.761904762, 'gross_income': 33.512, 'rating': 5.1}, {'invoice_id': '595-11-5460', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Male', 'product_line': 'Health and beauty', 'unit_cost': 96.58, 'quantity': 2, '5pct_markup': 9.658, 'revenue': 202.818, 'date': '3/15/2019', 'time': '10:12', 'payment_method': 'Credit card', 'cogs': 193.16, 'gm_pct': 4.761904762, 'gross_income': 9.658, 'rating': 5.1}, {'invoice_id': '183-56-6882', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Food and beverages', 'unit_cost': 99.42, 'quantity': 4, '5pct_markup': 19.884, 'revenue': 417.564, 'date': '02/06/19', 'time': '10:42', 'payment_method': 'Ewallet', 'cogs': 397.68, 'gm_pct': 4.761904762, 'gross_income': 19.884, 'rating': 7.5}, {'invoice_id': '232-16-2483', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Sports and travel', 'unit_cost': 68.12, 'quantity': 1, '5pct_markup': 3.406, 'revenue': 71.526, 'date': '01/07/19', 'time': '12:28', 'payment_method': 'Ewallet', 'cogs': 68.12, 'gm_pct': 4.761904762, 'gross_income': 3.406, 'rating': 6.8}, {'invoice_id': '129-29-8530', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Sports and travel', 'unit_cost': 62.62, 'quantity': 5, '5pct_markup': 15.655, 'revenue': 328.755, 'date': '03/10/19', 'time': '19:15', 'payment_method': 'Ewallet', 'cogs': 313.1, 'gm_pct': 4.761904762, 'gross_income': 15.655, 'rating': 7.0}, {'invoice_id': '272-65-1806', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Electronic accessories', 'unit_cost': 60.88, 'quantity': 9, '5pct_markup': 27.396, 'revenue': 575.316, 'date': '1/15/2019', 'time': '17:17', 'payment_method': 'Ewallet', 'cogs': 547.92, 'gm_pct': 4.761904762, 'gross_income': 27.396, 'rating': 4.7}, {'invoice_id': '333-73-7901', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Normal', 'gender_customer': 'Female', 'product_line': 'Health and beauty', 'unit_cost': 54.92, 'quantity': 8, '5pct_markup': 21.968, 'revenue': 461.328, 'date': '3/23/2019', 'time': '13:24', 'payment_method': 'Ewallet', 'cogs': 439.36, 'gm_pct': 4.761904762, 'gross_income': 21.968, 'rating': 7.6}, {'invoice_id': '777-82-7220', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Home and lifestyle', 'unit_cost': 30.12, 'quantity': 8, '5pct_markup': 12.048, 'revenue': 253.008, 'date': '03/03/19', 'time': '13:01', 'payment_method': 'Cash', 'cogs': 240.96, 'gm_pct': 4.761904762, 'gross_income': 12.048, 'rating': 7.7}, {'invoice_id': '280-35-5823', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Home and lifestyle', 'unit_cost': 86.72, 'quantity': 1, '5pct_markup': 4.336, 'revenue': 91.056, 'date': '1/17/2019', 'time': '18:45', 'payment_method': 'Ewallet', 'cogs': 86.72, 'gm_pct': 4.761904762, 'gross_income': 4.336, 'rating': 7.9}, {'invoice_id': '554-53-8700', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Home and lifestyle', 'unit_cost': 56.11, 'quantity': 2, '5pct_markup': 5.611, 'revenue': 117.831, 'date': '02/02/19', 'time': '10:11', 'payment_method': 'Cash', 'cogs': 112.22, 'gm_pct': 4.761904762, 'gross_income': 5.611, 'rating': 6.3}, {'invoice_id': '354-25-5821', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Sports and travel', 'unit_cost': 69.12, 'quantity': 6, '5pct_markup': 20.736, 'revenue': 435.456, 'date': '02/08/19', 'time': '13:03', 'payment_method': 'Cash', 'cogs': 414.72, 'gm_pct': 4.761904762, 'gross_income': 20.736, 'rating': 5.6}, {'invoice_id': '228-96-1411', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Food and beverages', 'unit_cost': 98.7, 'quantity': 8, '5pct_markup': 39.48, 'revenue': 829.08, 'date': '03/04/19', 'time': '20:39', 'payment_method': 'Cash', 'cogs': 789.6, 'gm_pct': 4.761904762, 'gross_income': 39.48, 'rating': 7.6}, {'invoice_id': '617-15-4209', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Health and beauty', 'unit_cost': 15.37, 'quantity': 2, '5pct_markup': 1.537, 'revenue': 32.277, 'date': '3/16/2019', 'time': '19:47', 'payment_method': 'Cash', 'cogs': 30.74, 'gm_pct': 4.761904762, 'gross_income': 1.537, 'rating': 7.2}, {'invoice_id': '132-32-9879', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Electronic accessories', 'unit_cost': 93.96, 'quantity': 4, '5pct_markup': 18.792, 'revenue': 394.632, 'date': '03/09/19', 'time': '18:00', 'payment_method': 'Cash', 'cogs': 375.84, 'gm_pct': 4.761904762, 'gross_income': 18.792, 'rating': 9.5}, {'invoice_id': '370-41-7321', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Health and beauty', 'unit_cost': 56.69, 'quantity': 9, '5pct_markup': 25.5105, 'revenue': 535.7205, 'date': '2/27/2019', 'time': '17:24', 'payment_method': 'Credit card', 'cogs': 510.21, 'gm_pct': 4.761904762, 'gross_income': 25.5105, 'rating': 8.4}, {'invoice_id': '727-46-3608', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Food and beverages', 'unit_cost': 20.01, 'quantity': 9, '5pct_markup': 9.0045, 'revenue': 189.0945, 'date': '02/06/19', 'time': '15:47', 'payment_method': 'Ewallet', 'cogs': 180.09, 'gm_pct': 4.761904762, 'gross_income': 9.0045, 'rating': 4.1}, {'invoice_id': '669-54-1719', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Electronic accessories', 'unit_cost': 18.93, 'quantity': 6, '5pct_markup': 5.679, 'revenue': 119.259, 'date': '02/10/19', 'time': '12:45', 'payment_method': 'Credit card', 'cogs': 113.58, 'gm_pct': 4.761904762, 'gross_income': 5.679, 'rating': 8.1}, {'invoice_id': '574-22-5561', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Fashion accessories', 'unit_cost': 82.63, 'quantity': 10, '5pct_markup': 41.315, 'revenue': 867.615, 'date': '3/19/2019', 'time': '17:08', 'payment_method': 'Ewallet', 'cogs': 826.3, 'gm_pct': 4.761904762, 'gross_income': 41.315, 'rating': 7.9}, {'invoice_id': '326-78-5178', 'branch': 'C', 'city': 'Naypyitaw', 'customer_type': 'Member', 'gender_customer': 'Male', 'product_line': 'Food and beverages', 'unit_cost': 91.4, 'quantity': 7, '5pct_markup': 31.99, 'revenue': 671.79, 'date': '02/03/19', 'time': '10:19', 'payment_method': 'Cash', 'cogs': 639.8, 'gm_pct': 4.761904762, 'gross_income': 31.99, 'rating': 9.5}, {'invoice_id': '162-48-8011', 'branch': 'A', 'city': 'Yangon', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Food and beverages', 'unit_cost': 44.59, 'quantity': 5, '5pct_markup': 11.1475, 'revenue': 234.0975, 'date': '02/10/19', 'time': '15:10', 'payment_method': 'Cash', 'cogs': 222.95, 'gm_pct': 4.761904762, 'gross_income': 11.1475, 'rating': 8.5}, {'invoice_id': '616-24-2851', 'branch': 'B', 'city': 'Mandalay', 'customer_type': 'Member', 'gender_customer': 'Female', 'product_line': 'Fashion accessories', 'unit_cost': 17.87, 'quantity': 4, '5pct_markup': 3.574, 'reve

In [8]:
## Mostrar el reporte de las ventas
#for: El ciclo recorre cada venta en el diccionario
print("=== REPORTE DE VENTAS ===")
for datos in ventas[0]:  # Ingresando al diccionario
    print(f"ID_Factura: {datos['invoice_id']},Sucursal: {datos['branch']},Ciudad: {datos['city']},Tipo_Cliente: {datos['customer_type']},Genero_Cliente: {datos['gender_customer']},Línea_Producto: {datos['product_line']},Costo_Unitario: {datos['unit_cost']},Cantidad: {datos['quantity']},Beneficio%5: {datos['5pct_markup']},Ganacia: {datos['revenue']},Fecha: {datos['date']},Tiempo: {datos['time']},Metodo_Pago: {datos['payment_method']},Costo_total: {datos['cogs']},%Margen_Bruto: {datos['gm_pct']},Ingresos: {datos['gross_income']},Calificacion_compra: {datos['rating']} ")

=== REPORTE DE VENTAS ===
ID_Factura: 750-67-8428,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Health and beauty,Costo_Unitario: 74.69,Cantidad: 7,Beneficio%5: 26.1415,Ganacia: 548.9715,Fecha: 01/05/19,Tiempo: 13:08,Metodo_Pago: Ewallet,Costo_total: 522.83,%Margen_Bruto: 4.761904762,Ingresos: 26.1415,Calificacion_compra: 9.1
ID_Factura: 226-31-3081,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Electronic accessories,Costo_Unitario: 15.28,Cantidad: 5,Beneficio%5: 3.82,Ganacia: 80.22,Fecha: 03/08/19,Tiempo: 10:29,Metodo_Pago: Cash,Costo_total: 76.4,%Margen_Bruto: 4.761904762,Ingresos: 3.82,Calificacion_compra: 9.6
ID_Factura: 631-41-3108,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Home and lifestyle,Costo_Unitario: 46.33,Cantidad: 7,Beneficio%5: 16.2155,Ganacia: 340.5255,Fecha: 03/03/19,Tiempo: 13:23,Metodo_Pago: Credit card,Costo_total: 324.31,%Margen_Bruto: 4.761904762,Ingresos: 16.2155,Calificacion_compra: 7.4
ID_Factura: 123-19-1176,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Health and beauty,Costo_Unitario: 58.22,Cantidad: 8,Beneficio%5: 23.288,Ganacia: 489.048,Fecha: 1/27/2019,Tiempo: 20:33,Metodo_Pago: Ewallet,Costo_total: 465.76,%Margen_Bruto: 4.761904762,Ingresos: 23.288,Calificacion_compra: 8.4
ID_Factura: 373-73-7910,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Sports and travel,Costo_Unitario: 86.31,Cantidad: 7,Beneficio%5: 30.2085,Ganacia: 634.3785,Fecha: 02/08/19,Tiempo: 10:37,Metodo_Pago: Ewallet,Costo_total: 604.17,%Margen_Bruto: 4.761904762,Ingresos: 30.2085,Calificacion_compra: 5.3
ID_Factura: 699-14-3026,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Electronic accessories,Costo_Unitario: 85.39,Cantidad: 7,Beneficio%5: 29.8865,Ganacia: 627.6165,Fecha: 3/25/2019,Tiempo: 18:30,Metodo_Pago: Ewallet,Costo_total: 597.73,%Margen_Bruto: 4.761904762,Ingresos: 29.8865,Calificacion_compra: 4.1
ID_Factura: 355-53-5943,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Electronic accessories,Costo_Unitario: 68.84,Cantidad: 6,Beneficio%5: 20.652,Ganacia: 433.692,Fecha: 2/25/2019,Tiempo: 14:36,Metodo_Pago: Ewallet,Costo_total: 413.04,%Margen_Bruto: 4.761904762,Ingresos: 20.652,Calificacion_compra: 5.8
ID_Factura: 315-22-5665,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Home and lifestyle,Costo_Unitario: 73.56,Cantidad: 10,Beneficio%5: 36.78,Ganacia: 772.38,Fecha: 2/24/2019,Tiempo: 11:38,Metodo_Pago: Ewallet,Costo_total: 735.6,%Margen_Bruto: 4.761904762,Ingresos: 36.78,Calificacion_compra: 8.0
ID_Factura: 665-32-9167,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Health and beauty,Costo_Unitario: 36.26,Cantidad: 2,Beneficio%5: 3.626,Ganacia: 76.146,Fecha: 01/10/19,Tiempo: 17:15,Metodo_Pago: Credit card,Costo_total: 72.52,%Margen_Bruto: 4.761904762,Ingresos: 3.626,Calificacion_compra: 7.2
ID_Factura: 692-92-5582,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Food and beverages,Costo_Unitario: 54.84,Cantidad: 3,Beneficio%5: 8.226,Ganacia: 172.746,Fecha: 2/20/2019,Tiempo: 13:27,Metodo_Pago: Credit card,Costo_total: 164.52,%Margen_Bruto: 4.761904762,Ingresos: 8.226,Calificacion_compra: 5.9
ID_Factura: 351-62-0822,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Fashion accessories,Costo_Unitario: 14.48,Cantidad: 4,Beneficio%5: 2.896,Ganacia: 60.816,Fecha: 02/06/19,Tiempo: 18:07,Metodo_Pago: Ewallet,Costo_total: 57.92,%Margen_Bruto: 4.761904762,Ingresos: 2.896,Calificacion_compra: 4.5
ID_Factura: 529-56-3974,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Electronic accessories,Costo_Unitario: 25.51,Cantidad: 4,Beneficio%5: 5.102,Ganacia: 107.142,Fecha: 03/09/19,Tiempo: 17:03,Metodo_Pago: Cash,Costo_total: 102.04,%Margen_Bruto: 4.761904762,Ingresos: 5.102,Calificacion_compra: 6.8
ID_Factura: 365-64-0515,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Electronic accessories,Costo_Unitario: 46.95,Cantidad: 5,Beneficio%5: 11.7375,Ganacia: 246.4875,Fecha: 02/12/19,Tiempo: 10:25,Metodo_Pago: Ewallet,Costo_total: 234.75,%Margen_Bruto: 4.761904762,Ingresos: 11.7375,Calificacion_compra: 7.1
ID_Factura: 252-56-2699,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Food and beverages,Costo_Unitario: 43.19,Cantidad: 10,Beneficio%5: 21.595,Ganacia: 453.495,Fecha: 02/07/19,Tiempo: 16:48,Metodo_Pago: Ewallet,Costo_total: 431.9,%Margen_Bruto: 4.761904762,Ingresos: 21.595,Calificacion_compra: 8.2
ID_Factura: 829-34-3910,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Health and beauty,Costo_Unitario: 71.38,Cantidad: 10,Beneficio%5: 35.69,Ganacia: 749.49,Fecha: 3/29/2019,Tiempo: 19:21,Metodo_Pago: Cash,Costo_total: 713.8,%Margen_Bruto: 4.761904762,Ingresos: 35.69,Calificacion_compra: 5.7
ID_Factura: 299-46-1805,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Sports and travel,Costo_Unitario: 93.72,Cantidad: 6,Beneficio%5: 28.116,Ganacia: 590.436,Fecha: 1/15/2019,Tiempo: 16:19,Metodo_Pago: Cash,Costo_total: 562.32,%Margen_Bruto: 4.761904762,Ingresos: 28.116,Calificacion_compra: 4.5
ID_Factura: 656-95-9349,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Health and beauty,Costo_Unitario: 68.93,Cantidad: 7,Beneficio%5: 24.1255,Ganacia: 506.6355,Fecha: 03/11/19,Tiempo: 11:03,Metodo_Pago: Credit card,Costo_total: 482.51,%Margen_Bruto: 4.761904762,Ingresos: 24.1255,Calificacion_compra: 4.6
ID_Factura: 765-26-6951,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Sports and travel,Costo_Unitario: 72.61,Cantidad: 6,Beneficio%5: 21.783,Ganacia: 457.443,Fecha: 01/01/19,Tiempo: 10:39,Metodo_Pago: Credit card,Costo_total: 435.66,%Margen_Bruto: 4.761904762,Ingresos: 21.783,Calificacion_compra: 6.9
ID_Factura: 329-62-1586,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Food and beverages,Costo_Unitario: 54.67,Cantidad: 3,Beneficio%5: 8.2005,Ganacia: 172.2105,Fecha: 1/21/2019,Tiempo: 18:00,Metodo_Pago: Credit card,Costo_total: 164.01,%Margen_Bruto: 4.761904762,Ingresos: 8.2005,Calificacion_compra: 8.6
ID_Factura: 319-50-3348,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Home and lifestyle,Costo_Unitario: 40.3,Cantidad: 2,Beneficio%5: 4.03,Ganacia: 84.63,Fecha: 03/11/19,Tiempo: 15:30,Metodo_Pago: Ewallet,Costo_total: 80.6,%Margen_Bruto: 4.761904762,Ingresos: 4.03,Calificacion_compra: 4.4
ID_Factura: 300-71-4605,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Electronic accessories,Costo_Unitario: 86.04,Cantidad: 5,Beneficio%5: 21.51,Ganacia: 451.71,Fecha: 2/25/2019,Tiempo: 11:24,Metodo_Pago: Ewallet,Costo_total: 430.2,%Margen_Bruto: 4.761904762,Ingresos: 21.51,Calificacion_compra: 4.8
ID_Factura: 371-85-5789,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Health and beauty,Costo_Unitario: 87.98,Cantidad: 3,Beneficio%5: 13.197,Ganacia: 277.137,Fecha: 03/05/19,Tiempo: 10:40,Metodo_Pago: Ewallet,Costo_total: 263.94,%Margen_Bruto: 4.761904762,Ingresos: 13.197,Calificacion_compra: 5.1
ID_Factura: 273-16-6619,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Home and lifestyle,Costo_Unitario: 33.2,Cantidad: 2,Beneficio%5: 3.32,Ganacia: 69.72,Fecha: 3/15/2019,Tiempo: 12:20,Metodo_Pago: Credit card,Costo_total: 66.4,%Margen_Bruto: 4.761904762,Ingresos: 3.32,Calificacion_compra: 4.4
ID_Factura: 636-48-8204,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Electronic accessories,Costo_Unitario: 34.56,Cantidad: 5,Beneficio%5: 8.64,Ganacia: 181.44,Fecha: 2/17/2019,Tiempo: 11:15,Metodo_Pago: Ewallet,Costo_total: 172.8,%Margen_Bruto: 4.761904762,Ingresos: 8.64,Calificacion_compra: 9.9
ID_Factura: 549-59-1358,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Sports and travel,Costo_Unitario: 88.63,Cantidad: 3,Beneficio%5: 13.2945,Ganacia: 279.1845,Fecha: 03/02/19,Tiempo: 17:36,Metodo_Pago: Ewallet,Costo_total: 265.89,%Margen_Bruto: 4.761904762,Ingresos: 13.2945,Calificacion_compra: 6.0
ID_Factura: 227-03-5010,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Home and lifestyle,Costo_Unitario: 52.59,Cantidad: 8,Beneficio%5: 21.036,Ganacia: 441.756,Fecha: 3/22/2019,Tiempo: 19:20,Metodo_Pago: Credit card,Costo_total: 420.72,%Margen_Bruto: 4.761904762,Ingresos: 21.036,Calificacion_compra: 8.5
ID_Factura: 649-29-6775,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Fashion accessories,Costo_Unitario: 33.52,Cantidad: 1,Beneficio%5: 1.676,Ganacia: 35.196,Fecha: 02/08/19,Tiempo: 15:31,Metodo_Pago: Cash,Costo_total: 33.52,%Margen_Bruto: 4.761904762,Ingresos: 1.676,Calificacion_compra: 6.7
ID_Factura: 189-17-4241,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Fashion accessories,Costo_Unitario: 87.67,Cantidad: 2,Beneficio%5: 8.767,Ganacia: 184.107,Fecha: 03/10/19,Tiempo: 12:17,Metodo_Pago: Credit card,Costo_total: 175.34,%Margen_Bruto: 4.761904762,Ingresos: 8.767,Calificacion_compra: 7.7
ID_Factura: 145-94-9061,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Food and beverages,Costo_Unitario: 88.36,Cantidad: 5,Beneficio%5: 22.09,Ganacia: 463.89,Fecha: 1/25/2019,Tiempo: 19:48,Metodo_Pago: Cash,Costo_total: 441.8,%Margen_Bruto: 4.761904762,Ingresos: 22.09,Calificacion_compra: 9.6
ID_Factura: 848-62-7243,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Health and beauty,Costo_Unitario: 24.89,Cantidad: 9,Beneficio%5: 11.2005,Ganacia: 235.2105,Fecha: 3/15/2019,Tiempo: 15:36,Metodo_Pago: Cash,Costo_total: 224.01,%Margen_Bruto: 4.761904762,Ingresos: 11.2005,Calificacion_compra: 7.4
ID_Factura: 871-79-8483,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Fashion accessories,Costo_Unitario: 94.13,Cantidad: 5,Beneficio%5: 23.5325,Ganacia: 494.1825,Fecha: 2/25/2019,Tiempo: 19:39,Metodo_Pago: Credit card,Costo_total: 470.65,%Margen_Bruto: 4.761904762,Ingresos: 23.5325,Calificacion_compra: 4.8
ID_Factura: 149-71-6266,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Sports and travel,Costo_Unitario: 78.07,Cantidad: 9,Beneficio%5: 35.1315,Ganacia: 737.7615,Fecha: 1/28/2019,Tiempo: 12:43,Metodo_Pago: Cash,Costo_total: 702.63,%Margen_Bruto: 4.761904762,Ingresos: 35.1315,Calificacion_compra: 4.5
ID_Factura: 640-49-2076,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Sports and travel,Costo_Unitario: 83.78,Cantidad: 8,Beneficio%5: 33.512,Ganacia: 703.752,Fecha: 01/10/19,Tiempo: 14:49,Metodo_Pago: Cash,Costo_total: 670.24,%Margen_Bruto: 4.761904762,Ingresos: 33.512,Calificacion_compra: 5.1
ID_Factura: 595-11-5460,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Health and beauty,Costo_Unitario: 96.58,Cantidad: 2,Beneficio%5: 9.658,Ganacia: 202.818,Fecha: 3/15/2019,Tiempo: 10:12,Metodo_Pago: Credit card,Costo_total: 193.16,%Margen_Bruto: 4.761904762,Ingresos: 9.658,Calificacion_compra: 5.1
ID_Factura: 183-56-6882,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Food and beverages,Costo_Unitario: 99.42,Cantidad: 4,Beneficio%5: 19.884,Ganacia: 417.564,Fecha: 02/06/19,Tiempo: 10:42,Metodo_Pago: Ewallet,Costo_total: 397.68,%Margen_Bruto: 4.761904762,Ingresos: 19.884,Calificacion_compra: 7.5
ID_Factura: 232-16-2483,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Sports and travel,Costo_Unitario: 68.12,Cantidad: 1,Beneficio%5: 3.406,Ganacia: 71.526,Fecha: 01/07/19,Tiempo: 12:28,Metodo_Pago: Ewallet,Costo_total: 68.12,%Margen_Bruto: 4.761904762,Ingresos: 3.406,Calificacion_compra: 6.8
ID_Factura: 129-29-8530,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Sports and travel,Costo_Unitario: 62.62,Cantidad: 5,Beneficio%5: 15.655,Ganacia: 328.755,Fecha: 03/10/19,Tiempo: 19:15,Metodo_Pago: Ewallet,Costo_total: 313.1,%Margen_Bruto: 4.761904762,Ingresos: 15.655,Calificacion_compra: 7.0
ID_Factura: 272-65-1806,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Electronic accessories,Costo_Unitario: 60.88,Cantidad: 9,Beneficio%5: 27.396,Ganacia: 575.316,Fecha: 1/15/2019,Tiempo: 17:17,Metodo_Pago: Ewallet,Costo_total: 547.92,%Margen_Bruto: 4.761904762,Ingresos: 27.396,Calificacion_compra: 4.7
ID_Factura: 333-73-7901,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Health and beauty,Costo_Unitario: 54.92,Cantidad: 8,Beneficio%5: 21.968,Ganacia: 461.328,Fecha: 3/23/2019,Tiempo: 13:24,Metodo_Pago: Ewallet,Costo_total: 439.36,%Margen_Bruto: 4.761904762,Ingresos: 21.968,Calificacion_compra: 7.6
ID_Factura: 777-82-7220,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Home and lifestyle,Costo_Unitario: 30.12,Cantidad: 8,Beneficio%5: 12.048,Ganacia: 253.008,Fecha: 03/03/19,Tiempo: 13:01,Metodo_Pago: Cash,Costo_total: 240.96,%Margen_Bruto: 4.761904762,Ingresos: 12.048,Calificacion_compra: 7.7
ID_Factura: 280-35-5823,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Home and lifestyle,Costo_Unitario: 86.72,Cantidad: 1,Beneficio%5: 4.336,Ganacia: 91.056,Fecha: 1/17/2019,Tiempo: 18:45,Metodo_Pago: Ewallet,Costo_total: 86.72,%Margen_Bruto: 4.761904762,Ingresos: 4.336,Calificacion_compra: 7.9
ID_Factura: 554-53-8700,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Home and lifestyle,Costo_Unitario: 56.11,Cantidad: 2,Beneficio%5: 5.611,Ganacia: 117.831,Fecha: 02/02/19,Tiempo: 10:11,Metodo_Pago: Cash,Costo_total: 112.22,%Margen_Bruto: 4.761904762,Ingresos: 5.611,Calificacion_compra: 6.3
ID_Factura: 354-25-5821,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Sports and travel,Costo_Unitario: 69.12,Cantidad: 6,Beneficio%5: 20.736,Ganacia: 435.456,Fecha: 02/08/19,Tiempo: 13:03,Metodo_Pago: Cash,Costo_total: 414.72,%Margen_Bruto: 4.761904762,Ingresos: 20.736,Calificacion_compra: 5.6
ID_Factura: 228-96-1411,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Food and beverages,Costo_Unitario: 98.7,Cantidad: 8,Beneficio%5: 39.48,Ganacia: 829.08,Fecha: 03/04/19,Tiempo: 20:39,Metodo_Pago: Cash,Costo_total: 789.6,%Margen_Bruto: 4.761904762,Ingresos: 39.48,Calificacion_compra: 7.6
ID_Factura: 617-15-4209,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Health and beauty,Costo_Unitario: 15.37,Cantidad: 2,Beneficio%5: 1.537,Ganacia: 32.277,Fecha: 3/16/2019,Tiempo: 19:47,Metodo_Pago: Cash,Costo_total: 30.74,%Margen_Bruto: 4.761904762,Ingresos: 1.537,Calificacion_compra: 7.2
ID_Factura: 132-32-9879,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Electronic accessories,Costo_Unitario: 93.96,Cantidad: 4,Beneficio%5: 18.792,Ganacia: 394.632,Fecha: 03/09/19,Tiempo: 18:00,Metodo_Pago: Cash,Costo_total: 375.84,%Margen_Bruto: 4.761904762,Ingresos: 18.792,Calificacion_compra: 9.5
ID_Factura: 370-41-7321,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Health and beauty,Costo_Unitario: 56.69,Cantidad: 9,Beneficio%5: 25.5105,Ganacia: 535.7205,Fecha: 2/27/2019,Tiempo: 17:24,Metodo_Pago: Credit card,Costo_total: 510.21,%Margen_Bruto: 4.761904762,Ingresos: 25.5105,Calificacion_compra: 8.4
ID_Factura: 727-46-3608,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Food and beverages,Costo_Unitario: 20.01,Cantidad: 9,Beneficio%5: 9.0045,Ganacia: 189.0945,Fecha: 02/06/19,Tiempo: 15:47,Metodo_Pago: Ewallet,Costo_total: 180.09,%Margen_Bruto: 4.761904762,Ingresos: 9.0045,Calificacion_compra: 4.1
ID_Factura: 669-54-1719,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Electronic accessories,Costo_Unitario: 18.93,Cantidad: 6,Beneficio%5: 5.679,Ganacia: 119.259,Fecha: 02/10/19,Tiempo: 12:45,Metodo_Pago: Credit card,Costo_total: 113.58,%Margen_Bruto: 4.761904762,Ingresos: 5.679,Calificacion_compra: 8.1
ID_Factura: 574-22-5561,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Fashion accessories,Costo_Unitario: 82.63,Cantidad: 10,Beneficio%5: 41.315,Ganacia: 867.615,Fecha: 3/19/2019,Tiempo: 17:08,Metodo_Pago: Ewallet,Costo_total: 826.3,%Margen_Bruto: 4.761904762,Ingresos: 41.315,Calificacion_compra: 7.9
ID_Factura: 326-78-5178,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Food and beverages,Costo_Unitario: 91.4,Cantidad: 7,Beneficio%5: 31.99,Ganacia: 671.79,Fecha: 02/03/19,Tiempo: 10:19,Metodo_Pago: Cash,Costo_total: 639.8,%Margen_Bruto: 4.761904762,Ingresos: 31.99,Calificacion_compra: 9.5
ID_Factura: 162-48-8011,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Food and beverages,Costo_Unitario: 44.59,Cantidad: 5,Beneficio%5: 11.1475,Ganacia: 234.0975,Fecha: 02/10/19,Tiempo: 15:10,Metodo_Pago: Cash,Costo_total: 222.95,%Margen_Bruto: 4.761904762,Ingresos: 11.1475,Calificacion_compra: 8.5
ID_Factura: 616-24-2851,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Member,Genero_Cliente: Female,Línea_Producto: Fashion accessories,Costo_Unitario: 17.87,Cantidad: 4,Beneficio%5: 3.574,Ganacia: 75.054,Fecha: 3/22/2019,Tiempo: 14:42,Metodo_Pago: Ewallet,Costo_total: 71.48,%Margen_Bruto: 4.761904762,Ingresos: 3.574,Calificacion_compra: 6.5
ID_Factura: 778-71-5554,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Fashion accessories,Costo_Unitario: 15.43,Cantidad: 1,Beneficio%5: 0.7715,Ganacia: 16.2015,Fecha: 1/25/2019,Tiempo: 15:46,Metodo_Pago: Credit card,Costo_total: 15.43,%Margen_Bruto: 4.761904762,Ingresos: 0.7715,Calificacion_compra: 6.1
ID_Factura: 242-55-6721,Sucursal: B,Ciudad: Mandalay,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Home and lifestyle,Costo_Unitario: 16.16,Cantidad: 2,Beneficio%5: 1.616,Ganacia: 33.936,Fecha: 03/07/19,Tiempo: 11:49,Metodo_Pago: Ewallet,Costo_total: 32.32,%Margen_Bruto: 4.761904762,Ingresos: 1.616,Calificacion_compra: 6.5
ID_Factura: 399-46-5918,Sucursal: C,Ciudad: Naypyitaw,Tipo_Cliente: Normal,Genero_Cliente: Female,Línea_Producto: Electronic accessories,Costo_Unitario: 85.98,Cantidad: 8,Beneficio%5: 34.392,Ganacia: 722.232,Fecha: 2/28/2019,Tiempo: 19:01,Metodo_Pago: Cash,Costo_total: 687.84,%Margen_Bruto: 4.761904762,Ingresos: 34.392,Calificacion_compra: 8.2
ID_Factura: 106-35-6779,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Member,Genero_Cliente: Male,Línea_Producto: Home and lifestyle,Costo_Unitario: 44.34,Cantidad: 2,Beneficio%5: 4.434,Ganacia: 93.114,Fecha: 3/27/2019,Tiempo: 11:26,Metodo_Pago: Cash,Costo_total: 88.68,%Margen_Bruto: 4.761904762,Ingresos: 4.434,Calificacion_compra: 5.8
ID_Factura: 635-40-6220,Sucursal: A,Ciudad: Yangon,Tipo_Cliente: Normal,Genero_Cliente: Male,Línea_Producto: Health and beauty,Costo_Unitario: 89.6,Cantidad: 8,Beneficio%5: 35.84,Ganacia: 752.64,Fecha: 02/07/19,Tiempo: 11:28,Metodo_Pago: Ewallet,Costo_total: 716.8,%Margen_Bruto: 4.761904762,Ingresos: 35.84,Calificacion_compra: 6.6

In [9]:
#Convertir el tipo de la variable date
data['date'] = pd.to_datetime(data['date'], format='%m/%d/%y', errors='coerce')
data['date'] = data['date'].combine_first(pd.to_datetime(data['date'], format='%m/%d/%Y', errors='coerce'))

# Extraer componentes de fecha y hora
data['day_of_week'] = data['date'].dt.day_name()
data['hour'] = data['time'].str.split(':').str[0].astype(int)

data.head()

,invoice_id,branch,city,customer_type,gender_customer,product_line,unit_cost,quantity,5pct_markup,revenue,date,time,payment_method,cogs,gm_pct,gross_income,rating,day_of_week,hour
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08,Ewallet,522.83,4.761905,26.1415,9.1,Saturday,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29,Cash,76.40,4.761905,3.8200,9.6,Friday,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23,Credit card,324.31,4.761905,16.2155,7.4,Sunday,13
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,NaT,20:33,Ewallet,465.76,4.761905,23.2880,8.4,NaN,20
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Friday,10

### **📊 Análisis Exploratorio de Datos (EDA)** <a name="eda"></a>